### ISSUE TITLE
snake case optional for all Uppercase 

### ISSUE THREAD

**Issue by mkoenings** [MeltanoLabs/Singer-Working-Group#34]
I work with Snowflake databases, where all tables, schemas etc are Uppercase. This leads to funny names when loading the data straight into mssql, because all names get "snakecased"  so from ABC we get a_b_c.
This happens in the conform_name function  in singer_sdk/sinks/sql.py , which is applied to all names. Can we change that so its optional ? Alternatively, the snakecase function should ignore all uppercase names.

**Comment by tayloramurphy** [comment]
@mkoenings this is more appropriate for the https://github.com/meltano/sdk/ repo. Can you open an issue there if this is still an issue for you?
